#!/bin/sh

# 'Supervize'. Keep track of your devices infos.
# Copyright © 2013-2021 Mathias Bocquet <mbocquet@sekoya.org>

# Dependencies :
# ping, netcat (nc)

if [ $# -lt 1 ]
then
    printf "Syntax : $(basename $0) <file> [ports list]\n"
    printf "<file> contains lines of pairs devices ip\n"
    printf "like :\n"
    printf "mydeviceinDNS mydeviceinDNS\n"
    printf "mydevicenotinDNS 10.45.23.12\n"
    printf "[ports list] can be either 'ssh http' or '22 80'\n"
    exit 1
else
    FILE=$1
    shift
    PORTS=$*
fi

# Colors
green='\033[0;32m'
blinkred='\033[0;31;5m'
red='\033[0;31m'
reset='\033[0m'

#ok="✪"     # star
#failed="☢" # radioactivity
#ok="●"     # full circle
#failed="●" # full circle

# ok is brighter than failed
ok="■"     # big filled square (u2b1b)
failed="□" # big square (u2b1c)

# failed is brighter than ok
#ok="□"     # big filled square (u2b1b)
#failed="■" # big square (u2b1c)

ICMP_TIMEOUT=1
PORT_TIMEOUT=1

printf "%-16s %-40s%-6s" "Device" "ipaddr" "up"
for PORT in $PORTS
do
    printf "%-6s" "$PORT"
done
printf "\n"

while read DEVICE IP
do
    case $DEVICE in
    # if our device line is empty or contains only spaces then print only
    # a newline
    ''|\s)
        printf "\n"
        continue
        ;;
    # if our device begins with a hash, we ignore it, its a comment !
    \#*)
        continue
        ;;
    esac
    printf ${reset}"%-16s %-40s" $DEVICE $IP
    if ping -c 1 -W ${ICMP_TIMEOUT} $IP >/dev/null 2>&1
    then
        printf "${green}%-8s" "$ok"
    else
        printf "${red}%-8s" "$failed"
    fi
    for PORT in $PORTS
    do
        if nc -z -w ${PORT_TIMEOUT} $IP $PORT >/dev/null 2>&1
        then
            printf "${green}%-8s" "$ok"
        else
            printf "${red}%-8s" "$failed"
        fi
    done
    printf ${reset}"\n"
done<$FILE
